### PR TITLE
add image scans for storage service in CSM for Authorization

### PR DESCRIPTION
**Pull request by alikdell**
# Description
add image scans for storage service in CSM for Authorization.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| #https://github.com/dell/csm/issues/243 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

image

### CODE REVIEW

**Review by shaynafinocchiaro — DISMISSED** [review]

**Review by atye — APPROVED** [review]

**Review by shaynafinocchiaro — APPROVED** [review]

**Comment by alikdell** [comment]
run e2e test

**Comment by AronAtDell** [comment]
Why are we making these changes now? Thanks!

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
E2E pass

**Comment by alikdell** [comment]
rune2e test

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Pull request merged**
