### PR TITLE
allow permissive for selinux install

### PR DESCRIPTION
**Pull request by arnchiequ-dell**
# Description
Install k3s-SELinux when SELinux is in permissive mode.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|dell/csm#409|

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Tested with SELinux in permissive mode
- [x] Tested with SELinux in enabled mode
- [x] Tested with SELinux in disabled mode

### CODE REVIEW

**Comment by arnchiequ-dell** [comment]
e2e test

**Comment by arnchiequ-dell** [comment]
run e2e test

**Review by alikdell — APPROVED** [review]

**Comment by arnchiequ-dell** [comment]
run e2e test

**Comment by arnchiequ-dell** [comment]
run e2e test

**Pull request merged**
