### PR TITLE
Ubi micro image implementation 

### PR DESCRIPTION
**Pull request by IsaiasA1**
# Description
Updating existing image to ubi-micro and use of podman and buildah

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/922 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Powerflex rpm installation
13 scenarios (13 passed)
98 steps (98 passed)
18m43.102221192s
2023/07/20 10:38:51 Volume test finished

Powerflex helm installation
13 scenarios (13 passed)
98 steps (98 passed)
18m28.513592944s
2023/07/20 11:29:19 Volume test finished

Powerscale rpm installation
3 scenarios (3 passed)
27 steps (27 passed)
4m48.437515964s
2023/07/20 12:08:14 Volume test finished

Powerscale helm installation
3 scenarios (3 passed)
27 steps (27 passed)
5m7.737859408s
2023/07/20 12:23:42 Volume test finished

Powermax rpm installation
8 scenarios (8 passed)
74 steps (74 passed)
9m51.86078202s
2023/07/24 13:11:42 Volume test finished

Powermax helm installation
8 scenarios (8 passed)
74 steps (74 passed)
14m30.223519298s
2023/07/24 14:38:38 Volume test finished

### CODE REVIEW

**Review by PeresKereotubo — DISMISSED** [review]

**Review by shaynafinocchiaro — DISMISSED** [review]

**Review by atye — APPROVED** [review]

**Comment by xuluna** [comment]
run e2e test

**Review by alikdell — APPROVED** [review]

**Review by PeresKereotubo — APPROVED** [review]

**Comment by xuluna** [comment]
run e2e test

**Review by xuluna — APPROVED** [review]

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Comment by xuluna** [comment]
run e2e test

**Pull request merged**
