### PR TITLE
[feature-725]: Remove tenant service ingress

### PR DESCRIPTION
**Pull request by atye**
# Description
This PR removes the tenant-service ingress from the RPM, adds tenant-service handlers to the proxy-server, updates `karavictl` to connect to the proxy-server instead of the tenant-service, and adds telemetry updates.

**Proxy-Server changes:**

New tenant handler at `internal/proxy/tenant_handler.go` to handle these paths for `karavictl`:

```
POST /proxy/tenant/ (create tenant, tenant info is in request body)
PATCH /proxy/tenant/ (update tenant, tenant info is in request body)
GET /proxy/tenant/ (list or get tenant, tenant name is in query parameter)
DELETE /proxy/tenant/ (delete tenant, name is in query parameter)
POST /proxy/tenant/bind/ (tenant and role info is in request body)
POST /proxy/tenant/unbind/ (tenant and role info is in request body)
POST /proxy/tenant/token/ (tenant and token info is in request body)
PATCH /proxy/tenant/revoke/ (tenant and revoke info is in request body)
```

The handlers for each path will parse the request and make the appropriate grpc request to the tenant service.

Adds grpc connection interceptors which will automatically create tracing spans for grpc client requests.

New http middleware called `TelemetryMW`. This will log the time taken for the next handler to complete and record the error in the span. The telemetry will happen only if the next handler is the type `HandlerWithError`. This handler returns an error specifically for recording in the span.

`type HandlerWithError func(w http.ResponseWriter, r *http.Request) error`

**karavictl changes:**

- `karavictl` commands that previously connected to the tenant-service via grpc now connect to the proxy-server via https
- New file `cmd/karavictl/cmd/api/api.go` which is a generic http client inspired by https://github.com/dell/goscaleio/blob/main/api/api.go
- `karavictl` will build this generic http client and execute the appropriate request

**Tenant-service changes:**

- Adds grpc server interceptors which will automatically create tracing spans for incoming requests.
- Adds telemetry middleware at `internal/tenantsvc/middleware/telemetry.go` to log the time taken for the request, log request info, and set the request info in the span

# GitHub Issues

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/725|

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

New unit tests, manual testing, manual e2e tests.

### CODE REVIEW

**Review by alikdell — APPROVED** [review]

**Review by shaynafinocchiaro — APPROVED** [review]

**Review by alikdell — APPROVED** [review]

**Review by shaynafinocchiaro — DISMISSED** [review]

**Comment by atye** [comment]
run e2e test

**Comment by atye** [comment]
run e2e test

**Comment by atye** [comment]
run e2e test

**Comment by atye** [comment]
run e2e test

**Comment by atye** [comment]
run e2e test

**Review by xuluna — APPROVED** [review]

**Review by alikdell — APPROVED** [review]

**Comment by atye** [comment]
run e2e test pass

**Comment by atye** [comment]
run e2e test pass

**Comment by xuluna** [comment]
> run e2e test pass

where can you see these commands?

**Comment by atye** [comment]
e2e pass

**Review by shaynafinocchiaro — APPROVED** [review]

**Comment by atye** [comment]
e2e pass

**Pull request merged**
