### PR TITLE
[feature-743]: Remove busybox from RPM

### PR DESCRIPTION
**Pull request by atye**
# Description

- Removes busybox from RPM deployment
- Standardize telemetry span names for karavictl handlers
- Update some comments

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/743 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Manual deployment of RPM.

### CODE REVIEW

**Review by alikdell — APPROVED** [review]

**Comment by atye** [comment]
run e2e test

**Comment by atye** [comment]
run e2e test

**Comment by atye** [comment]
run e2e test

**Comment by atye** [comment]
e2e pass

**Pull request merged**
