### PR TITLE
bundle busy-box with one binary

### PR DESCRIPTION
**Pull request by medegw01**
# Description

PR bundles busy-box with one binary.

# Issues

List the issues impacted by this PR:

| Issue ID |
| -------- |
|      N/A   |

# Checklist:

- [x] I have performed a self-review of my own changes.

### CODE REVIEW

**Comment by ioeicicdsvc** [comment]
@medegw01: Thank you for submitting your pull request!

Please make sure you have followed our contributing guidelines. We will review it as soon as possible.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Review by ianbibby — CHANGES_REQUESTED** [review]
Since this busybox container is only there to pull in busybox as a dependency, we should leave a comment stating this.  In the future we can seek how to bundle this more effectively.

**Comment by medegw01** [comment]
> Since this busybox container is only there to pull in busybox as a dependency, we should leave a comment stating this. In the future we can seek how to bundle this more effectively.

@ianbibby addressed

**Review by ianbibby — APPROVED** [review]

**Review by atye — APPROVED** [review]

**Review by tdawe — APPROVED** [review]

**Review by tdawe — CHANGES_REQUESTED** [review]
Removing approval

**Review by tdawe — APPROVED** [review]

**Pull request merged**
