### PR TITLE
update to 1.7

### PR DESCRIPTION
**Pull request by IsaiasA1**
# Description
Updating docker and sidecar tags to 1.7.0

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/743 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

-N/A

### CODE REVIEW

**Review by arnchiequ-dell — APPROVED** [review]

**Review by PeresKereotubo — APPROVED** [review]

**Comment by IsaiasA1** [comment]
run e2e test

**Review by shaynafinocchiaro — APPROVED** [review]

**Review by alikdell — APPROVED** [review]

**Comment by IsaiasA1** [comment]
run e2e test

**Comment by IsaiasA1** [comment]
Run e2e pass

**Comment by IsaiasA1** [comment]
e2e pass

**Pull request merged**
