### PR TITLE
moving defer close into functions

### PR DESCRIPTION
**Pull request by arnchiequ-dell**
# Description
Unsafe to defer close because it may throw an error. This causes gosec to error out.  Containing it within a function with an error check is safer.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/409 |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [X] Did a fresh install on VM and everything worked properly

### CODE REVIEW

**Review by sharmilarama — APPROVED** [review]

**Review by shaynafinocchiaro — APPROVED** [review]

**Comment by sharmilarama** [comment]
run e2e test

**Comment by sharmilarama** [comment]
run e2e test

**Comment by sharmilarama** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by arnchiequ-dell** [comment]
e2e pass

**Pull request merged**
