### PR TITLE
Updating headers

### PR DESCRIPTION
**Pull request by IsaiasA1**
# Description
Updated Headers of source code files (go, DockerFile, rego, md, and MakeFiles) to reflect that of the project template (https://eos2git.cec.lab.emc.com/DevCon/NewProjectTemplate/blob/master/README.md)

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|dell/csm#491|

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Verified using E2E test

### CODE REVIEW

**Comment by IsaiasA1** [comment]
run e2e test

**Review by shaynafinocchiaro — DISMISSED** [review]

**Review by sharmilarama — APPROVED** [review]

**Comment by IsaiasA1** [comment]
run e2e test

**Comment by IsaiasA1** [comment]
run e2e test

**Comment by IsaiasA1** [comment]
run e2e test

**Comment by IsaiasA1** [comment]
run e2e test

**Review by hoppea2 — APPROVED** [review]

**Review by shaynafinocchiaro — APPROVED** [review]

**Review by atye — APPROVED** [review]

**Comment by IsaiasA1** [comment]
run e2e test

**Comment by alikdell** [comment]
run e2e test

**Review by sharmilarama — APPROVED** [review]

**Comment by IsaiasA1** [comment]
run e2e test

**Comment by IsaiasA1** [comment]
run e2e test

**Pull request merged**
