### PR TITLE
update linter go version

### PR DESCRIPTION
**Pull request by cbartoszDell**
- Update of go version in linter action.
- Remove gosec from linter. gosec is already being run in the go_security_scan. This is to avoid `G402: TLS InsecureSkipVerify set true. (gosec)` linter error
- Adds `make lint` for automating linting fixes, when possible

### CODE REVIEW

**Review by shaynafinocchiaro — APPROVED** [review]

**Review by donatwork — APPROVED** [review]

**Comment by cbartoszDell** [comment]
This PR is only for upgrading the versions on Go and golangci-lint action. This is required to make sure that golangci-lint is always the latest version and is working with the latest version of Go. This requests is being made to all CSM drivers and modules to make sure linter action keeps working. Fixing linter warnings is not a part of scope of this upgrade PR.

**Review by xuluna — DISMISSED** [review]

**Review by KerryKovacevic — DISMISSED** [review]

**Review by atye — DISMISSED** [review]

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Review by shefali-malhotra — DISMISSED** [review]
LGTM

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Review by KerryKovacevic — APPROVED** [review]

**Review by xuluna — APPROVED** [review]

**Review by alikdell — APPROVED** [review]

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Pull request merged**
