### PR TITLE
Upgrade Go and package dependencies

### PR DESCRIPTION
**Pull request by shaynafinocchiaro**
# Description

- This PR removes the deprecated io/ioutil and Open Telemetry packages
- Updates all direct dependencies
- Updates to Go 1.21
- Uses default metrics for prometheus. We can access more metrics by implementing an open telemetry prometheus exporter and collector. 

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/916|

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Deployed authorization and created storage
- [x] Spin up a prometheus endpoint to retrieve metrics 
Capture
- [x] Manual Helm e2e
```
11 scenarios ([32m11 passed[0m)
89 steps ([32m89 passed[0m)
9m47.343461108s
2023/08/22 12:41:37 Volume test finished

1 scenarios ([32m1 passed[0m)
2 steps ([32m2 passed[0m)
3m11.324085553s
2023/08/22 12:44:48 Validation test finished
--- PASS: TestAuthCleanUP (191.34s)
PASS
```

### CODE REVIEW

**Review by xuluna — APPROVED** [review]

**Review by atye — APPROVED** [review]

**Review by xuluna — APPROVED** [review]

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Review by alikdell — DISMISSED** [review]

**Review by atye — APPROVED** [review]

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Review by alikdell — APPROVED** [review]

**Review by PeresKereotubo — DISMISSED** [review]

**Review by atye — DISMISSED** [review]

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Review by xuluna — APPROVED** [review]

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
run e2e test

**Comment by shaynafinocchiaro** [comment]
Manually ran e2e for helm. Results in description

**Comment by shaynafinocchiaro** [comment]
e2e pass

**Comment by shaynafinocchiaro** [comment]
e2e pass

**Pull request merged**
